// Generated by CoffeeScript 1.6.3
/*
# modal
*/


(function() {
  (function($, UI, _) {
    var Modal;
    Modal = function(element, options) {};
    return UI['modal'] = Modal;
  })(jQuery, jQuery.adama, jQuery.adama.utils);

}).call(this);
