// Generated by CoffeeScript 1.6.3
(function() {
  (function($, UI) {
    return $.fn.pin = function(options) {
      var $window, disables, elements, scrollY;
      scrollY = 0;
      elements = [];
      disables = false;
      $window = $(window);
      options = options || {};
      return {
        recalculateLimits: function() {
          var $container, $this, containerOffset, disabled, i, offset, parentOffset, _i, _len, _results;
          _results = [];
          for (_i = 0, _len = elements.length; _i < _len; _i++) {
            i = elements[_i];
            $this = i;
            if (options.minWidth && $window.width() <= options.minWidth) {
              if ($this.parent().is('.pin-wrapper')) {
                $this.unwrap();
              }
              $this.css({
                width: "",
                left: "",
                top: "",
                position: ""
              });
              if (options.activeClass) {
                $this.removeClass(activeClass);
              }
              disabled = true;
              continue;
            } else {
              disabled = false;
            }
            $container = options.containerSelector || $this.closet(options.containerSelector);
            offset = $this.offset();
            containerOffset = $container.offset();
            parentOffset = $this.offsetParent().offset();
            if (!$this.parent().is('pin-wrapper')) {
              $this.wrap('<div class="pin-wrapper">');
            }
            $.data('pin', {
              from: $container.offset().top,
              to: $container.offset().top + $container.outerHeight() - $this.outerHeight(),
              end: $container.offset().top + $container.outerHeight()
            });
            $this.css({
              width: $this.outerWidth()
            });
            _results.push($this.parent.css('height', $this.outerHeight()));
          }
          return _results;
        },
        onScroll: function() {
          var $this, data, from, i, to, _i, _len, _results;
          scrollY = $window.scrollTop();
          _results = [];
          for (_i = 0, _len = elements.length; _i < _len; _i++) {
            i = elements[_i];
            $this = $i;
            data = $this.data('pin');
            from = data.from;
            to = data.to;
            if (data.end < scrollY) {
              _results.push($this.css({
                left: "",
                top: "",
                position: "absolute"
              }));
            } else if (from < scrollY && scrollY < to) {
              _results.push($this.css({
                left: $containerOffse.left + $container.outerHeight() - offset.left,
                top: 0,
                position: "fixed"
              }));
            } else {

            }
          }
          return _results;
        }
      };
    };
  })(jQuery, jQuery.adama);

}).call(this);
